### PR TITLE
Added device manager for custom drivers

### PR DESCRIPTION
**Pull request by Jemetzner**
I have added a device manager to handle drivers for custom lab setups. The wand server code is modified to call the switch and osa driver modules from the configuration file. Currently the drivers for the laser system and Wavemeter are left alone, but could be easily added to the configuration file.

The device manager follows the same system used in [artiq](https://github.com/m-labs/artiq).

### CODE REVIEW

**Comment by hartytp** [comment]
The examples are not updating, so I assume this breaks them? No comment here on what changes need to be applied to existing setups to continue working ether.

Beyond that, it feels like you've dragged in a lot more code from artiq than is needed here. Do we need a device db? does it need to be a notifier?

**Comment by Jemetzner** [comment]
These are good points. I will add commits for the examples. All that is necessary is adding the module, class and class arguments to the server configuration for the OSA and switch, as the example will show. Otherwise, this should require no changes to existing setups.

The device db is not necessary and I will go ahead and scrap that from the Device manager, otherwise everything else is necessary.

**Comment by hartytp** [comment]
This PR makes me pretty uncomfortable overall. Trying to articulate why that is...

From the discussions we've had it's really not clear to me how widely the stuff you're doing is likely to be useful v whether it's a hack for your lab (which is fine but should live happily in your fork). I'm okay with adding a bit of extra flexibility in the code structure to support what you want to do if we can do it with sufficiently low cost. However, I'm also very mindful of the cost of every line of code we add to the codebase in terms of complexity/room for bugs/maintenance burden.

At present I feel that the utility of what you want to do doesn't justify the downsides. To shift that we either need to really improve the quality of the implementation (in particular strip it down to the minimum part that's actually useful for what we want to achieve) or put more discussion into justifying why this is something which should be in the main codebase v your fork.

Being totally up front with you, I'm also struggling with the signal to noise of these PRs which still feels a bit low (why would we ever have wanted a device db with a notifier etc?). There is a lot of stuff that I'd ideally like to do to this codebase but don't have time for. When I see a decent complexity PR for a feature request that I don't really understand the chance of a review/merge happening in finite time isn't high.

**Comment by Jemetzner** [comment]
Thank you for taking the time to provide feedback on my pull request. I will definitely take what you have said to make better pull requests in the future.

Based on our discussion about adding a more flexible option for supporting different setups it was my understanding that specifying the device drivers to the configuration file was the near term goal. I believe that without the device db, which is certainly superfluous, this code is minimal and useful. If you think adding this flexibility is still worthwhile, I will fix up my issues and improve my signal to noise, otherwise you can go ahead and close this pull request.

**Comment by dtcallcock** [comment]
> a feature request that I don't really understand 

The basic idea is that WAND should be able to support different and changing hardware without requiring every lab to maintain their own fork.  Now I can see that if we're the only people outside of Oxford you ever anticipate using WAND this is not worth your dealing with.  Hopefully we can make it minimally invasive though.

**Comment by hartytp** [comment]
> Now I can see that if we're the only people outside of Oxford you ever anticipate using WAND this may not worth your dealing with

I think there are other people outside Oxford using WaND but the perennial problem with these projects is that none of them have been in contact so I don't have any insight into what they're doing/want, which does make it hard to asses how valuable features will ultimately be if they're not solving one of our immediate problems.

> Hopefully we can make it minimally invasive though.

If we can get this change down to a few lines (which is what I ultimately think it should be) then it would be more compelling

**Pull request closed without merging**
